### ISSUE TITLE
Suggestion: Document exactly what is bad about the BAD_CT_SERVERS

### ISSUE THREAD

**Issue by Kagee** [CaliDog/certstream-server-python#11]
https://github.com/CaliDog/certstream-server/blob/fbf82d11d283b6f2a8f566b1b2873e4f1c81e2b1/certstream/watcher.py#L12

**Comment by invisiblethreat** [comment]
I'm also curious what makes a bad CT server.

**Comment by Fitblip** [comment]
Hey folks,

This was a blacklist that I maintained while developing CertStream originally, the google API had a number of CT servers that were unavailable, so instead of spending cycles to try to constantly talk to a server that was never going to work I optioned to just blacklist them.

This is probably not the case anymore, but I will leave this ticket open until I can get around to re-testing!

Cheers,
Ryan

**Comment by Fitblip** [comment]
This is now explained with a comment (and an updated list of bad CTLs).

https://github.com/CaliDog/certstream-server/blob/419b2524cdf80fed420d24afb1fdc1d81a10824a/certstream/watcher.py#L12-L36

Thanks for the suggestion!
