### ISSUE TITLE
Support Checkpointing of stream

### ISSUE THREAD

**Issue by patrobinson** [CaliDog/certstream-server-python#5]
Currently if you stop and re-start the stream, you start from the beginning. To be truly useful the stream should allow you to supply a marker, say the `cert_index`, to start receiving the stream from.

**Comment by Fitblip** [comment]
Hey @patrobinson!

> Currently if you stop and re-start the stream, you start from the beginning.

Certstream is designed to be stateless, meaning that we only broadcast certificates to the currently connected clients, then discard them from memory, so there's not really a "beginning" or "end" to it. It was designed this way because it was cost-prohibitive to actually build a more traditional REST API on top of it that would support a pagination scheme like you suggest, and still have it be a free service. As awesome as it'd be (and it's definitely doable) it'd require a pretty large Kafka queue/datastore to actually pull it off, which requires a decent chunk of cost I'm not willing to incur right now. If you have any ideas on how to do this on the cheap though I'm happy to support the use case!

Now, having said that, while building out my company's flagship product (https://phishfinder.io - in free/open beta right now) I wanted to have this data be part of our analytics pipeline, so I *do* scrape and batch process all these certificates to a BigQuery dataset every day, which is used in the product itself. 

![image](https://user-images.githubusercontent.com/1072598/32457201-261d5bc8-c2dd-11e7-8d25-6fc7bba4796a.png)

If you'd like, I'm happy to share the table with you so you can run you own queries! Also if you're interested in building a similar system or how I built the ingest pipeline, I did a 2 part writeup as well - https://medium.com/cali-dog-security/retrieving-storing-and-querying-250m-certificates-like-a-boss-31b1ce2dfcf8.

Hope it helps!

**Comment by patrobinson** [comment]
Thanks @Fitblip, that's an interesting way to solve the problem. We already have mechanisms to feed this kind of data down a Kinesis Stream and read it so we'd prefer to treat this data the same.

I tried reading the code, but I don't quite understand how it works. How does the Cert Stream server maintain the entire list of certificate updates? Or does it just keep the last n updates?

**Comment by Fitblip** [comment]
> How does the Cert Stream server maintain the entire list of certificate updates?

We don't, CertStream Server basically just polls all the CTLs looking for changes in the merkle tree size, and once it's changed goes and fetches the certificates that were added, then pipes them to the connected clients.

We do have a ring buffer that holds the most recent 25 certs we've seen and feeds the `/latest.json` and `/develop` endpoints, but that's about it. 

Maybe I misunderstand what you mean by "the entire list of certificate updates"?

**Comment by patrobinson** [comment]
Nah I think I'm confused, thanks for the explanation. I wonder how I can extract the consumption of the CTL and utilise it to feed into my own streaming queue, but that's an exercise for another day. Thanks very much.

**Comment by Fitblip** [comment]
Sounds good, let me know if I can help further! Have a great rest of your week :).
