### ISSUE TITLE
Adding all logs?

### ISSUE THREAD

**Issue by quirins** [CaliDog/certstream-server-python#8]
Hi,

I am huge fan of this and congratulate on the nice API! This is more a question than an issue:

The server seems to currently only load the currently/formerly trusted logs, instead of all logs [1].

Have you tested using all logs and if this would lead to performance issues?
Do you have a URL that a client can connect to that provides data from all logs?

Thank you!
Kind regards
Quirin

[1] line 46 in watcher.py:
 self.transparency_logs = requests.get('https://www.gstatic.com/ct/log_list/log_list.json').json()
should probably be 
 self.transparency_logs = requests.get('https://www.gstatic.com/ct/log_list/all_logs_list.json').json()
to read all logs.

**Comment by heipei** [comment]
I would agree with this. I know that a lot of people are probably eager to use certstream.io (the service, not the software) to discover phishing and other malicious content. For this, logs like the Let's Encrypt one are crucial. Maybe my understanding of CT is flawed, and certs issued by LE are already included in some of the Google logs. In any case: Thanks for the great service and making the code Open Source!

**Comment by Fitblip** [comment]
Hey @quirins - Huge apologies for not responding quickly, I'm not sure how this fell off my radar!

> I am huge fan of this and congratulate on the nice API! This is more a question than an issue:

Thanks!

> The server seems to currently only load the currently/formerly trusted logs, instead of all logs [1].

Yep, this was more a symptom of the original implementation being written while the CTL API was in flux, they didn't have 2 endpoints when this was originally written!

> Have you tested using all logs and if this would lead to performance issues?

I haven't, but I'm happy to!

> Do you have a URL that a client can connect to that provides data from all logs?

Nope, but I'll just change it and flip it into prod later today! 

@heipei 

> I know that a lot of people are probably eager to use certstream.io (the service, not the software) to discover phishing and other malicious content.

Yessir, that's why it was made! 

> For this, logs like the Let's Encrypt one are crucial. Maybe my understanding of CT is flawed, and certs issued by LE are already included in some of the Google logs.

They are indeed already being streamed from certstream today, LetsEncrypt was really one of the core targets of this project. 

> In any case: Thanks for the great service and making the code Open Source!

No, thank *you* for not only using this service, but giving me valuable feedback!

**Comment by Fitblip** [comment]
Hey guys, this should be live now! Thanks again for the feedback :)
